### ISSUE TITLE
Follow/acknowledge XDG Base Directory Spec

### ISSUE THREAD

**Issue by Alliegaytor** [ManApart/starfield-mod-manager#2]
Hi, really like the project. Just have a little nit-pick with the config files.

When I ran it and started using it, it made a `config.json` in my `$HOME` dir even though my `$XDG_CONFIG_HOME` is set to `~/.config`. This isn't a major problem for me (my home dir is irrevocably tainted with random files), but I know some people really can't stand random dot files cluttering their home that there was a spec made for that.

https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

https://wiki.archlinux.org/title/XDG_Base_Directory (easier to read)

I propose something that follows this (or similar) order when checking for configs:

1. Check if `~/config.json` exists; if so, use that (compatibility for if the config was made before)
2. Check if `$XDG_CONFIG_HOME` is set; if so, use that
3. Check if `~/.config` exists; if so, use that
4. If all else fails `$HOME` or `./` would probably be fine

**Comment by ManApart** [comment]
Hey Alliegaytor. That's an interesting thought I hadn't considered.

At this point both the config file and the data file (where mod data is stored) are _both_ stored wherever you place the jar. This was done because 1) it was simple and 2) the idea was that then this is "portable" and "self contained". The expectation was that people would place it in a folder somewhere and then you have all the files in one place.

That said, current behavior is NOT to save it in the home directory; I assume it's just there because that's where your jar is.

I wouldn't be opposed to keeping current behavior _unless_ you have  `XDG_CONFIG_HOME` set and if so then do `XDG_CONFIG_HOME/config.json`. Does that make sense?

**Comment by Alliegaytor** [comment]
Ok that makes a lot of sense! I hadn't placed the jar in my home directory, but I ran `java -jar ~/path/to/starfield-mod-manager.jar` while I was in my home. I thought it would either place the config with the jar or at `XDG_CONFIG_HOME` and not the directory I was in.

I think having it continue to be portable, but allowing people to set `XDG_CONFIG_HOME` and using that would be a great idea. It'll give users more choice in how to set up the configs.

For my setup, I should just cd to where I want it to be first before running it. Simple enough :)

**Comment by ManApart** [comment]
Ok, latest master now allows you to set a folder path using an env of something like `XDG_CONFIG_HOME=~/Downloads`.

In the case that you use that env variable, the `config.json` will be named `starfield-mod-manager-config.json` so as to avoid naming conflicts. (You can copy the existing config over and rename it, or transplant the json inside etc).

Could you pull and gradle build jar and let me know if it works for you? If so, I'll close the issue.

**Comment by Alliegaytor** [comment]
I built from master and can confirm that the config file location can be set with `XDG_CONFIG_HOME` and it's now called `starfield-mod-manager-config.json`. Thanks!

**Comment by ManApart** [comment]
Glad it worked. Thanks for creating the detailed issue!
